version: '3.8'

services:
  postgres_db:
    image: postgres:15
    container_name: smart_logistics_pg
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: HelloYoutube
      POSTGRES_DB: smart_logistics
    ports:
      - "5432:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  pgdata: 